IFC2X3 C++ SDK: Step::Array< T, _lo, _hi > Class Template Reference
Step::Array< T, _lo, _hi > Class Template Reference
C++ implementation of EXPRESS container 'ARRAY' we are using C vector wrapped into a stl environment instead of an std::vector.
Inherits Step::Aggregate.
typedef std::reverse_iterator
< iterator > reverse_iterator
reverse iterator support
typedef std::reverse_iterator
< const_iterator > const_reverse_iterator
reverse_iterator rbegin ()
const_reverse_iterator rbegin () const
reverse_iterator rend ()
const_reverse_iterator rend () const
Public Types
typedef T value_type
fixed-size array of elements of type T
typedef T * iterator
typedef const T * const_iterator
typedef T & reference
typedef const T & const_reference
typedef Integer size_type
typedef std::ptrdiff_t difference_type
Public Member Functions
void swap (Array< T, _lo, _hi > &y)
swap (note: linear complexity)
T * c_array ()
use array as C array (direct read/write access to data)
template<typename T2>
Array< T, _lo, _hi > & operator= (const Array< T2, _lo, _hi > &rhs)
assignment with type conversion
void assign (const T &value)
assign one value to all elements
iterator begin ()
iterator support
const_iterator begin () const
iterator end ()
const_iterator end () const
Array (bool unset=false)
constructors
Array (const std::vector< T > &vec)
reference operator[] (size_type i)
operator[]
const_reference operator[] (size_type i) const
reference at (size_type i)
at() with range check
const_reference at (size_type i) const
reference front ()
front() and back()
const_reference front () const
reference back ()
const_reference back () const
const T * data () const
direct access to data (read-only)
T * data ()
bool operator< (const Array &rhs) const
comparison operators
bool operator== (const Array &rhs) const
Static Public Member Functions
static size_type size ()
size is constant
static bool empty ()
static size_type max_size ()
Static Protected Member Functions
static void checkRange (Integer idx)
check range
Protected Attributes
T _values [static_size]
storage of the values
Detailed Description
template<typename T, Integer _lo, Integer _hi>
class Step::Array< T, _lo, _hi >
C++ implementation of EXPRESS container 'ARRAY' we are using C vector wrapped into a stl environment instead of an std::vector.
Member Typedef Documentation
template<typename T, Integer _lo, Integer _hi> typedef T Step::Array< T, _lo, _hi >::value_type
fixed-size array of elements of type T
type definitions
template<typename T, Integer _lo, Integer _hi> typedef T* Step::Array< T, _lo, _hi >::iterator
template<typename T, Integer _lo, Integer _hi> typedef const T* Step::Array< T, _lo, _hi >::const_iterator
template<typename T, Integer _lo, Integer _hi> typedef T& Step::Array< T, _lo, _hi >::reference
template<typename T, Integer _lo, Integer _hi> typedef const T& Step::Array< T, _lo, _hi >::const_reference
template<typename T, Integer _lo, Integer _hi> typedef Integer Step::Array< T, _lo, _hi >::size_type
template<typename T, Integer _lo, Integer _hi> typedef std::ptrdiff_t Step::Array< T, _lo, _hi >::difference_type
template<typename T, Integer _lo, Integer _hi> typedef std::reverse_iterator<iterator> Step::Array< T, _lo, _hi >::reverse_iterator
reverse iterator support
template<typename T, Integer _lo, Integer _hi> typedef std::reverse_iterator<const_iterator> Step::Array< T, _lo, _hi >::const_reverse_iterator
Constructor & Destructor Documentation
template<typename T, Integer _lo, Integer _hi> Step::Array< T, _lo, _hi >::Array (bool unset = false) [inline]
constructors
template<typename T, Integer _lo, Integer _hi> Step::Array< T, _lo, _hi >::Array (const std::vector< T > & vec) [inline]
References Step::Array< T, _lo, _hi >::begin().
Member Function Documentation
template<typename T, Integer _lo, Integer _hi> iterator Step::Array< T, _lo, _hi >::begin () [inline]
iterator support
References Step::Array< T, _lo, _hi >::_values.
Referenced by Step::Array< T, _lo, _hi >::Array(), Step::Array< T, _lo, _hi >::assign(), Step::Array< T, _lo, _hi >::operator=(), Step::Array< T, _lo, _hi >::rend(), and Step::Array< T, _lo, _hi >::swap().
template<typename T, Integer _lo, Integer _hi> const_iterator Step::Array< T, _lo, _hi >::begin () const [inline]
References Step::Array< T, _lo, _hi >::_values.
template<typename T, Integer _lo, Integer _hi> iterator Step::Array< T, _lo, _hi >::end () [inline]
References Step::Array< T, _lo, _hi >::_values.
Referenced by Step::Array< T, _lo, _hi >::operator=(), Step::Array< T, _lo, _hi >::rbegin(), and Step::Array< T, _lo, _hi >::swap().
template<typename T, Integer _lo, Integer _hi> const_iterator Step::Array< T, _lo, _hi >::end () const [inline]
References Step::Array< T, _lo, _hi >::_values.
template<typename T, Integer _lo, Integer _hi> reverse_iterator Step::Array< T, _lo, _hi >::rbegin () [inline]
References Step::Array< T, _lo, _hi >::end().
template<typename T, Integer _lo, Integer _hi> const_reverse_iterator Step::Array< T, _lo, _hi >::rbegin () const [inline]
References Step::Array< T, _lo, _hi >::end().
template<typename T, Integer _lo, Integer _hi> reverse_iterator Step::Array< T, _lo, _hi >::rend () [inline]
References Step::Array< T, _lo, _hi >::begin().
template<typename T, Integer _lo, Integer _hi> const_reverse_iterator Step::Array< T, _lo, _hi >::rend () const [inline]
References Step::Array< T, _lo, _hi >::begin().
template<typename T, Integer _lo, Integer _hi> reference Step::Array< T, _lo, _hi >::operator[] (size_type i) [inline]
operator[]
References Step::Array< T, _lo, _hi >::_values, and Step::Array< T, _lo, _hi >::checkRange().
template<typename T, Integer _lo, Integer _hi> const_reference Step::Array< T, _lo, _hi >::operator[] (size_type i) const [inline]
References Step::Array< T, _lo, _hi >::_values, and Step::Array< T, _lo, _hi >::checkRange().
template<typename T, Integer _lo, Integer _hi> reference Step::Array< T, _lo, _hi >::at (size_type i) [inline]
at() with range check
References Step::Array< T, _lo, _hi >::_values, and Step::Array< T, _lo, _hi >::checkRange().
template<typename T, Integer _lo, Integer _hi> const_reference Step::Array< T, _lo, _hi >::at (size_type i) const [inline]
References Step::Array< T, _lo, _hi >::_values, and Step::Array< T, _lo, _hi >::checkRange().
template<typename T, Integer _lo, Integer _hi> reference Step::Array< T, _lo, _hi >::front () [inline]
front() and back()
References Step::Array< T, _lo, _hi >::_values.
template<typename T, Integer _lo, Integer _hi> const_reference Step::Array< T, _lo, _hi >::front () const [inline]
References Step::Array< T, _lo, _hi >::_values.
template<typename T, Integer _lo, Integer _hi> reference Step::Array< T, _lo, _hi >::back () [inline]
References Step::Array< T, _lo, _hi >::_values.
template<typename T, Integer _lo, Integer _hi> const_reference Step::Array< T, _lo, _hi >::back () const [inline]
References Step::Array< T, _lo, _hi >::_values.
template<typename T, Integer _lo, Integer _hi> static size_type Step::Array< T, _lo, _hi >::size () [inline, static]
size is constant
Referenced by Step::Array< T, _lo, _hi >::assign().
template<typename T, Integer _lo, Integer _hi> static bool Step::Array< T, _lo, _hi >::empty () [inline, static]
template<typename T, Integer _lo, Integer _hi> static size_type Step::Array< T, _lo, _hi >::max_size () [inline, static]
template<typename T, Integer _lo, Integer _hi> void Step::Array< T, _lo, _hi >::swap (Array< T, _lo, _hi > & y) [inline]
swap (note: linear complexity)
References Step::Array< T, _lo, _hi >::begin(), and Step::Array< T, _lo, _hi >::end().
template<typename T, Integer _lo, Integer _hi> const T* Step::Array< T, _lo, _hi >::data () const [inline]
direct access to data (read-only)
References Step::Array< T, _lo, _hi >::_values.
template<typename T, Integer _lo, Integer _hi> T* Step::Array< T, _lo, _hi >::data () [inline]
References Step::Array< T, _lo, _hi >::_values.
template<typename T, Integer _lo, Integer _hi> T* Step::Array< T, _lo, _hi >::c_array () [inline]
use array as C array (direct read/write access to data)
References Step::Array< T, _lo, _hi >::_values.
template<typename T, Integer _lo, Integer _hi> template<typename T2> Array<T,_lo,_hi>& Step::Array< T, _lo, _hi >::operator= (const Array< T2, _lo, _hi > & rhs) [inline]
assignment with type conversion
References Step::Array< T, _lo, _hi >::begin(), and Step::Array< T, _lo, _hi >::end().
template<typename T, Integer _lo, Integer _hi> void Step::Array< T, _lo, _hi >::assign (const T & value) [inline]
assign one value to all elements
References Step::Array< T, _lo, _hi >::begin(), and Step::Array< T, _lo, _hi >::size().
template<typename T, Integer _lo, Integer _hi> bool Step::Array< T, _lo, _hi >::operator< (const Array< T, _lo, _hi > & rhs) const [inline]
comparison operators
References Step::Array< T, _lo, _hi >::_values.
template<typename T, Integer _lo, Integer _hi> bool Step::Array< T, _lo, _hi >::operator== (const Array< T, _lo, _hi > & rhs) const [inline]
References Step::Array< T, _lo, _hi >::_values.
template<typename T, Integer _lo, Integer _hi> static void Step::Array< T, _lo, _hi >::checkRange (Integer idx) [inline, static, protected]
check range
Referenced by Step::Array< T, _lo, _hi >::at(), and Step::Array< T, _lo, _hi >::operator[]().
Member Data Documentation
template<typename T, Integer _lo, Integer _hi> T Step::Array< T, _lo, _hi >::_values[static_size] [protected]
storage of the values
Referenced by Step::Array< T, _lo, _hi >::at(), Step::Array< T, _lo, _hi >::back(), Step::Array< T, _lo, _hi >::begin(), Step::Array< T, _lo, _hi >::c_array(), Step::Array< T, _lo, _hi >::data(), Step::Array< T, _lo, _hi >::end(), Step::Array< T, _lo, _hi >::front(), Step::Array< T, _lo, _hi >::operator<(), Step::Array< T, _lo, _hi >::operator==(), and Step::Array< T, _lo, _hi >::operator[]().