#ifdef ENABLE_PRECOMPILED_HEADER
#include <Step/ASCII_codes.h>
#include <Step/Aggregation.h>
#include <Step/Array.h>
#include <Step/Bag.h>
#include <Step/BaseCopyOp.h>
#include <Step/BaseEntity.h>
#include <Step/BaseExpressDataSet.h>
#include <Step/BaseObject.h>
#include <Step/BaseSPFObject.h>
#include <Step/BaseSPFReader.h>
#include <Step/BaseSPFWriter.h>
#include <Step/BaseVisitor.h>
#include <Step/Binary.h>
#include <Step/ClassType.h>
#include <Step/ClientData.h>
#include <Step/ClientDataHandler.h>
#include <Step/List.h>
#include <Step/RefLinkedList.h>
#include <Step/Referenced.h>
#include <Step/SPFData.h>
#include <Step/SPFFunctions.h>
#include <Step/SPFHeader.h>
#include <Step/Set.h>
#include <Step/SimpleTypes.h>
#include <Step/StepExport.h>
#include <Step/String.h>
#include <Step/Types.h>
#include <Step/logger.h> 
#include <ifc2x3/all.h>
#endif