IFC2X3 C++ SDK: Step::List< T, _lo, _hi > Class Template Reference
Step::List< T, _lo, _hi > Class Template Reference
C++ implementation of EXPRESS container 'LIST' see http://tools.openoffice.org/performance/aggregate_classes.html we are using STL vectors instead of lists to favorise sequential access.
Inherits std::vector< T >, and Step::Aggregate.
Inherited by ifc2x3::Inverted_IfcCompositeCurve_Segments_type, ifc2x3::Inverted_IfcConstraintAggregationRelationship_RelatedConstraints_type, ifc2x3::Inverted_IfcGrid_UAxes_type, ifc2x3::Inverted_IfcGrid_VAxes_type, ifc2x3::Inverted_IfcGrid_WAxes_type, ifc2x3::Inverted_IfcMaterialLayerSet_MaterialLayers_type, ifc2x3::Inverted_IfcOrganization_Addresses_type, ifc2x3::Inverted_IfcPerson_Addresses_type, ifc2x3::Inverted_IfcProductRepresentation_Representations_type, ifc2x3::Inverted_IfcShapeAspect_ShapeRepresentations_type, ifc2x3::Inverted_IfcTable_Rows_type, and ifc2x3::Inverted_IfcVirtualGridIntersection_IntersectingAxes_type.
Public Types
typedef std::vector< T >::iterator iterator
the forward iterator
typedef std::vector< T >
::const_iterator const_iterator
the const forward iterator
typedef std::vector< T >
::reverse_iterator reverse_iterator
the reverse iterator
typedef std::vector< T >
::const_reverse_iterator const_reverse_iterator
the const reverse iterator
Public Member Functions
List (bool unset=false)
default constructor
List (const T value[], Integer count) throw (std::range_error)
List (const std::list< T > &value) throw (std::range_error)
virtual ~List ()
destructor
virtual void resize (Integer newsize, const T &_val=getUnset(T())) throw (std::out_of_range)
virtual iterator insert (iterator &it, const T &_val=getUnset(T()))
virtual iterator erase (iterator &idx)
virtual iterator erase (const T &_val)
virtual void insert (Integer idx, const T &_val=getUnset(T()))
virtual T & at (Integer idx)
virtual const T & at (Integer idx) const
virtual T & operator[] (Integer idx)
virtual const T & operator[] (Integer idx) const
virtual void push_back (const T &_val) throw (std::out_of_range)
virtual iterator erase (Integer idx) throw (std::out_of_range)
virtual Integer getUpperBound ()
virtual Integer getLowerBound ()
List & operator= (const List &other)
Protected Member Functions
virtual void checkRange (Integer idx) const throw (std::out_of_range)
Detailed Description
template<typename T, Integer _lo = 0, Integer _hi = -1>
class Step::List< T, _lo, _hi >
C++ implementation of EXPRESS container 'LIST' see http://tools.openoffice.org/performance/aggregate_classes.html we are using STL vectors instead of lists to favorise sequential access.
Member Typedef Documentation
template<typename T, Integer _lo = 0, Integer _hi = -1> typedef std::vector<T>::iterator Step::List< T, _lo, _hi >::iterator
the forward iterator
Reimplemented in ifc2x3::Inverted_IfcCompositeCurve_Segments_type, ifc2x3::Inverted_IfcConstraintAggregationRelationship_RelatedConstraints_type, ifc2x3::Inverted_IfcGrid_UAxes_type, ifc2x3::Inverted_IfcGrid_VAxes_type, ifc2x3::Inverted_IfcGrid_WAxes_type, ifc2x3::Inverted_IfcMaterialLayerSet_MaterialLayers_type, ifc2x3::Inverted_IfcOrganization_Addresses_type, ifc2x3::Inverted_IfcPerson_Addresses_type, ifc2x3::Inverted_IfcProductRepresentation_Representations_type, ifc2x3::Inverted_IfcShapeAspect_ShapeRepresentations_type, ifc2x3::Inverted_IfcTable_Rows_type, and ifc2x3::Inverted_IfcVirtualGridIntersection_IntersectingAxes_type.
template<typename T, Integer _lo = 0, Integer _hi = -1> typedef std::vector<T>::const_iterator Step::List< T, _lo, _hi >::const_iterator
the const forward iterator
template<typename T, Integer _lo = 0, Integer _hi = -1> typedef std::vector<T>::reverse_iterator Step::List< T, _lo, _hi >::reverse_iterator
the reverse iterator
template<typename T, Integer _lo = 0, Integer _hi = -1> typedef std::vector<T>::const_reverse_iterator Step::List< T, _lo, _hi >::const_reverse_iterator
the const reverse iterator
Constructor & Destructor Documentation
template<typename T, Integer _lo = 0, Integer _hi = -1> Step::List< T, _lo, _hi >::List (bool unset = false) [inline]
default constructor
template<typename T, Integer _lo = 0, Integer _hi = -1> Step::List< T, _lo, _hi >::List (const T value[], Integer count) throw (std::range_error) [inline]
constructor based on a array of T
template<typename T, Integer _lo = 0, Integer _hi = -1> Step::List< T, _lo, _hi >::List (const std::list< T > & value) throw (std::range_error) [inline]
constructor based on a std::list of T
template<typename T, Integer _lo = 0, Integer _hi = -1> virtual Step::List< T, _lo, _hi >::~List () [inline, virtual]
destructor
Member Function Documentation
template<typename T, Integer _lo = 0, Integer _hi = -1> virtual void Step::List< T, _lo, _hi >::resize (Integer newsize, const T & _val = getUnset(T())) throw (std::out_of_range) [inline, virtual]
Referenced by Step::IfcAddress >, 1 >::List().
template<typename T, Integer _lo = 0, Integer _hi = -1> virtual iterator Step::List< T, _lo, _hi >::insert (iterator & it, const T & _val = getUnset(T())) [inline, virtual]
template<typename T, Integer _lo = 0, Integer _hi = -1> virtual iterator Step::List< T, _lo, _hi >::erase (iterator & idx) [inline, virtual]
template<typename T, Integer _lo = 0, Integer _hi = -1> virtual iterator Step::List< T, _lo, _hi >::erase (const T & _val) [inline, virtual]
template<typename T, Integer _lo = 0, Integer _hi = -1> virtual void Step::List< T, _lo, _hi >::insert (Integer idx, const T & _val = getUnset(T())) [inline, virtual]
template<typename T, Integer _lo = 0, Integer _hi = -1> virtual T& Step::List< T, _lo, _hi >::at (Integer idx) [inline, virtual]
template<typename T, Integer _lo = 0, Integer _hi = -1> virtual const T& Step::List< T, _lo, _hi >::at (Integer idx) const [inline, virtual]
template<typename T, Integer _lo = 0, Integer _hi = -1> virtual T& Step::List< T, _lo, _hi >::operator[] (Integer idx) [inline, virtual]
template<typename T, Integer _lo = 0, Integer _hi = -1> virtual const T& Step::List< T, _lo, _hi >::operator[] (Integer idx) const [inline, virtual]
template<typename T, Integer _lo = 0, Integer _hi = -1> virtual void Step::List< T, _lo, _hi >::push_back (const T & _val) throw (std::out_of_range) [inline, virtual]
template<typename T, Integer _lo = 0, Integer _hi = -1> virtual iterator Step::List< T, _lo, _hi >::erase (Integer idx) throw (std::out_of_range) [inline, virtual]
template<typename T, Integer _lo = 0, Integer _hi = -1> virtual Integer Step::List< T, _lo, _hi >::getUpperBound () [inline, virtual]
template<typename T, Integer _lo = 0, Integer _hi = -1> virtual Integer Step::List< T, _lo, _hi >::getLowerBound () [inline, virtual]
template<typename T, Integer _lo = 0, Integer _hi = -1> List& Step::List< T, _lo, _hi >::operator= (const List< T, _lo, _hi > & other) [inline]
template<typename T, Integer _lo = 0, Integer _hi = -1> virtual void Step::List< T, _lo, _hi >::checkRange (Integer idx) const throw (std::out_of_range) [inline, protected, virtual]
Referenced by Step::IfcAddress >, 1 >::at(), Step::IfcAddress >, 1 >::erase(), Step::IfcAddress >, 1 >::insert(), and Step::IfcAddress >, 1 >::operator[]().