IFC2X3 C++ SDK: Step::RefLinkedList_iterator< _Ty > Class Template Reference
Step::RefLinkedList_iterator< _Ty > Class Template Reference
Custom bidirectional iterator.
Public Types
typedef RefLinkedList< _Ty > RefLinkedList_type
typedef RefLinkedList< _Ty >
::element_type element_type
typedef
std::bidirectional_iterator_tag iterator_category
typedef _Ty value_type
typedef value_type & reference
typedef value_type * pointer
typedef int difference_type
Public Member Functions
RefLinkedList_iterator ()
RefLinkedList_iterator (unsigned int index, RefLinkedList_type *refLinkedList)
RefLinkedList_iterator (unsigned int index, RefLinkedList_type *refLinkedList, const typename element_type::iterator currentIt)
RefLinkedList_iterator (const RefLinkedList_iterator &it)
RefLinkedList_iterator & operator= (const RefLinkedList_iterator &it)
reference operator* () const
pointer operator-> () const
RefLinkedList_iterator & operator++ ()
RefLinkedList_iterator & operator-- ()
RefLinkedList_iterator operator++ (int)
RefLinkedList_iterator operator-- (int)
bool operator== (const RefLinkedList_iterator &_Right) const
bool operator!= (const RefLinkedList_iterator &_Right) const
Detailed Description
template<class _Ty>
class Step::RefLinkedList_iterator< _Ty >
Custom bidirectional iterator.
Member Typedef Documentation
template<class _Ty> typedef RefLinkedList<_Ty> Step::RefLinkedList_iterator< _Ty >::RefLinkedList_type
template<class _Ty> typedef RefLinkedList<_Ty>::element_type Step::RefLinkedList_iterator< _Ty >::element_type
template<class _Ty> typedef std::bidirectional_iterator_tag Step::RefLinkedList_iterator< _Ty >::iterator_category
template<class _Ty> typedef _Ty Step::RefLinkedList_iterator< _Ty >::value_type
template<class _Ty> typedef value_type& Step::RefLinkedList_iterator< _Ty >::reference
template<class _Ty> typedef value_type* Step::RefLinkedList_iterator< _Ty >::pointer
template<class _Ty> typedef int Step::RefLinkedList_iterator< _Ty >::difference_type
Constructor & Destructor Documentation
template<class _Ty> Step::RefLinkedList_iterator< _Ty >::RefLinkedList_iterator () [inline]
template<class _Ty> Step::RefLinkedList_iterator< _Ty >::RefLinkedList_iterator (unsigned int index, RefLinkedList_type * refLinkedList) [inline]
template<class _Ty> Step::RefLinkedList_iterator< _Ty >::RefLinkedList_iterator (unsigned int index, RefLinkedList_type * refLinkedList, const typename element_type::iterator currentIt) [inline]
template<class _Ty> Step::RefLinkedList_iterator< _Ty >::RefLinkedList_iterator (const RefLinkedList_iterator< _Ty > & it) [inline]
Member Function Documentation
template<class _Ty> RefLinkedList_iterator& Step::RefLinkedList_iterator< _Ty >::operator= (const RefLinkedList_iterator< _Ty > & it) [inline]
References Step::RefLinkedList_iterator< _Ty >::m_currentIt, Step::RefLinkedList_iterator< _Ty >::m_index, and Step::RefLinkedList_iterator< _Ty >::m_refLinkedList.
template<class _Ty> reference Step::RefLinkedList_iterator< _Ty >::operator* () const [inline]
References Step::BaseExpressDataSet::get(), Step::BaseSPFObject::getClassType(), Step::BaseObject::getExpressDataSet(), and Step::BaseObject::isOfType().
template<class _Ty> pointer Step::RefLinkedList_iterator< _Ty >::operator-> () const [inline]
template<class _Ty> RefLinkedList_iterator& Step::RefLinkedList_iterator< _Ty >::operator++ () [inline]
template<class _Ty> RefLinkedList_iterator& Step::RefLinkedList_iterator< _Ty >::operator-- () [inline]
template<class _Ty> RefLinkedList_iterator Step::RefLinkedList_iterator< _Ty >::operator++ (int) [inline]
template<class _Ty> RefLinkedList_iterator Step::RefLinkedList_iterator< _Ty >::operator-- (int) [inline]
template<class _Ty> bool Step::RefLinkedList_iterator< _Ty >::operator== (const RefLinkedList_iterator< _Ty > & _Right) const [inline]
References Step::RefLinkedList_iterator< _Ty >::m_currentIt, Step::RefLinkedList_iterator< _Ty >::m_index, and Step::RefLinkedList_iterator< _Ty >::m_refLinkedList.
template<class _Ty> bool Step::RefLinkedList_iterator< _Ty >::operator!= (const RefLinkedList_iterator< _Ty > & _Right) const [inline]