IFC2X3 C++ SDK: Step Namespace Reference
Step Namespace Reference
Classes
class Array
C++ implementation of EXPRESS container 'ARRAY' we are using C vector wrapped into a stl environment instead of an std::vector.
class Bag
C++ implementation of EXPRESS container 'BAG' based on multiset.
class BaseCopyOp
class BaseEntity
class BaseExpressDataSet
Base definition of a STEP ExpressDataSet.
class BaseObject
Base Object for Entity and Select definition.
class BaseSPFObject
Base Object of a STEP-21 file. It belongs to lazy loading concepts. A non-initialized object is an instance from BaseSPFObject.
class BaseSPFReader
Base class for loading a STEP-21 file. It reads header and entities.
class BaseSPFWriter
Base class to write a STEP-21 file from a Model.
class BaseVisitor
Base class of Visitor pattern.
class Binary
C++ Implementation of the EXPRESS Binary type.
class ClassType
Class to define an optimized type identifier.
class ClientData
A class which encapsulates user data of step objects. It contains meta-data.
class ClientDataHandler
A handler of ClientData.
class List
C++ implementation of EXPRESS container 'LIST' see http://tools.openoffice.org/performance/aggregate_classes.html we are using STL vectors instead of lists to favorise sequential access.
class Referenced
This class provides Reference counting objects. Instances should be used by RefPtr class.
class RefPtr
class Observer
class ObsPtr
class RefLinkedList_iterator
Custom bidirectional iterator.
class RefLinkedList
Custom bidirectional container.
class Set
C++ implementation of EXPRESS container 'SET' based on hash_set.
class Aggregate
Base Class for Aggregations which need a flag 'unset' This flag is used to distinguish a parameter with an empty list from an unset parameter.
class SPFData
Base Class to encapsulate data from a line of a STEP-21 file.
class SPFHeader
Defines the STEP-21 header.
class String
Typedefs
typedef long Integer
Integer type.
typedef double Real
Real type.
typedef Real Number
Number type.
typedef unsigned long int ClientDataKey
The ClientDataKey type definition.
typedef unsigned long int Id
The Id type definition.
typedef BaseEntity *(* AllocateFuncType)(BaseExpressDataSet *, Id)
The allocate function pointer type definition used by generated SPFReader.
typedef std::map< Id,
BaseEntityPtr > MapOfEntities
The map of entities type definition.
typedef RefPtr< BaseVisitor > BaseVisitorPtr
different typedef used by the generated classes
typedef RefPtr< BaseObject > BaseObjectPtr
typedef RefPtr< BaseEntity > BaseEntityPtr
typedef RefPtr< ClientData > ClientDataPtr
Enumerations
enum Boolean { BUnset, BFalse, BTrue }
Boolean type.
enum Logical { LUnset, LFalse, LTrue, LUnknown }
Logical type.
Functions
template<typename T, Integer _lo, Integer _hi>
Array< T, _lo, _hi > & getUnset (Array< T, _lo, _hi >)
UNSET for ARRAY.
template<typename T, Integer _lo, Integer _hi>
Bag< T, _lo, _hi > & getUnset (Bag< T, _lo, _hi >)
template<typename T, Integer _lo, Integer _hi>
List< T, _lo, _hi > & getUnset (List< T, _lo, _hi >)
return the UNSET value UNSET for LIST
template<typename T, Integer _lo, Integer _hi>
Set< T, _lo, _hi > & getUnset (Set< T, _lo, _hi >)
bool isUnset (const Unset &u)
String getUnset (const String &)
getUnset values the String type
const BaseObject * getUnset (const BaseObject *)
getUnset values the const BaseObject type
BaseObject * getUnset (BaseObject *)
template<typename T>
RefPtr< T > getUnset (RefPtr< T > &)
getUnset values the RefPtr type
Integer getUnset (Integer)
getUnset values the Integer type
Real getUnset (Real)
getUnset values the Real type
Boolean getUnset (Boolean)
getUnset values the Boolean type
Logical getUnset (Logical)
getUnset values the Logical type
template<int N>
Binary< N > getUnset (Binary< N >)
getUnset values the Binary type
bool isUnset (const String &v)
isUnset method for the String type
bool isUnset (const BaseObject *v)
isUnset method for the const BaseObject type
bool isUnset (BaseObject *v)
isUnset method for the BaseObject type
bool isUnset (Integer v)
isUnset method for the Integer type
bool isUnset (Real v)
isUnset method for the Real type
bool isUnsetEnum (int i)
isUnset method for the Enumerated type
bool isUnset (Boolean v)
isUnset method for the Boolean type
bool isUnset (Logical v)
isUnset method for the Logical type
template<int N>
bool isUnset (Binary< N > v)
isUnset method for the Binary type
bool isUnset (const Step::Aggregate &u)
isUnset method for the Aggregate type
template<typename T>
bool isUnset (RefPtr< T > &t)
isUnset method for the RefPtr type
Integer spfToInteger (const std::string &s)
spf parsing for Integer type
Real spfToReal (const std::string &s)
spf parsing for Real type
Boolean spfToBoolean (const std::string &s)
spf parsing for Boolean type
Logical spfToLogical (const std::string &s)
spf parsing for Logical type
template<int N>
Binary< N > spfToBinary (const std::string &s)
spf parsing for Bianry type
bool getSubParameter (std::string &arg, std::string &str1)
bool getLine (std::istream &ifs, unsigned int &counter, char *buffer, unsigned long bufferLength, std::string &str)
bool parseList (const char *buffer, std::vector< std::string > &res)
Id getIdParam (const std::string &s)
bool getIdListParam (const std::string &s, std::vector< Id > &res)
bool removeQuotes (std::string &s)
Variables
const char Apostrophe = 39
const char Ampersand = 38
const char Comma = 44
const char Colon = 58
const char Semicolon = 59
const char Slash = 47
const char BackSlash = 92
const char Space = 32
const char LeftParenthesis = 40
const char RightParenthesis = 41
const char Asterix = 42
const char DollarSign = 36
const char CrossHatch = 35
const char Underscore = 95
const char Period = 46
const char EqualSign = 61
const char LessSign = 60
const char GreaterSign = 62
const char QuestionMark = 63
const char QuoteMark = 34
const char PlusSign = 43
const char MinusSign = 45
const char LeftSquareBracket = 91
const char RightSquareBracket = 93
const char LeftBracket = 123
const char RightBracket = 125
const char VerticalSlash = 124
const char Hyphen = 45
const char Newline = 10
const char Return = 13
const unsigned long int Id_UNDEF = UINT_MAX
for error handling
const unsigned long int Id_UNSET = 0
for '$' token
Typedef Documentation
typedef BaseEntity*(* Step::AllocateFuncType)(BaseExpressDataSet *, Id)
The allocate function pointer type definition used by generated SPFReader.
typedef RefPtr<BaseEntity> Step::BaseEntityPtr
typedef RefPtr<BaseObject> Step::BaseObjectPtr
typedef RefPtr<BaseVisitor> Step::BaseVisitorPtr
different typedef used by the generated classes
typedef unsigned long int Step::ClientDataKey
The ClientDataKey type definition.
typedef RefPtr<ClientData> Step::ClientDataPtr
typedef unsigned long int Step::Id
The Id type definition.
typedef long Step::Integer
Integer type.
typedef std::map<Id, BaseEntityPtr > Step::MapOfEntities
The map of entities type definition.
typedef Real Step::Number
Number type.
typedef double Step::Real
Real type.
Enumeration Type Documentation
enum Step::Boolean
Boolean type.
Enumerator:
BUnset
BFalse
BTrue
enum Step::Logical
Logical type.
Enumerator:
LUnset
LFalse
LTrue
LUnknown
Function Documentation
bool Step::getIdListParam (const std::string & s, std::vector< Id > & res)
constructs a list of Ids from a string
Parameters:
s the string to parse
res the Step::Id (can be unset if $ is found
Returns:
success or failure
Id Step::getIdParam (const std::string & s)
returns the id from a string
Parameters:
s the string to parse
Returns:
the Step::Id (can be unset if $ is found
bool Step::getLine (std::istream & ifs, unsigned int & counter, char * buffer, unsigned long bufferLength, std::string & str)
reads a line from a ifstream until the ';' is found, update the line counter and uses the the buffer s to build the resulting string
Parameters:
ifs the input stream
counter the line counter that will be incremented by the number of EOL found
buffer the buffer to store the lines read directly from the ifs
bufferLength the length of the buffer
str the parsed line
Returns:
success or failure
bool Step::getSubParameter (std::string & arg, std::string & str1)
retrieves elements from a aggregate
Parameters:
arg the string to extract from
str1 the result of the extraction
Returns:
success
template<int N> Binary<N> Step::getUnset (Binary< N >) [inline]
getUnset values the Binary type
Logical Step::getUnset (Logical) [inline]
getUnset values the Logical type
References LUnset.
Boolean Step::getUnset (Boolean) [inline]
getUnset values the Boolean type
References BUnset.
Real Step::getUnset (Real) [inline]
getUnset values the Real type
Integer Step::getUnset (Integer) [inline]
getUnset values the Integer type
template<typename T> RefPtr<T> Step::getUnset (RefPtr< T > &) [inline]
getUnset values the RefPtr type
BaseObject* Step::getUnset (BaseObject *) [inline]
const BaseObject* Step::getUnset (const BaseObject *) [inline]
getUnset values the const BaseObject type
String Step::getUnset (const String &) [inline]
getUnset values the String type
template<typename T, Integer _lo, Integer _hi> Set<T,_lo,_hi>& Step::getUnset (Set< T, _lo, _hi >) [inline]
template<typename T, Integer _lo, Integer _hi> List<T,_lo,_hi>& Step::getUnset (List< T, _lo, _hi >) [inline]
return the UNSET value UNSET for LIST
template<typename T, Integer _lo, Integer _hi> Bag<T,_lo,_hi>& Step::getUnset (Bag< T, _lo, _hi >) [inline]
template<typename T, Integer _lo, Integer _hi> Array<T,_lo,_hi>& Step::getUnset (Array< T, _lo, _hi >) [inline]
UNSET for ARRAY.
Referenced by Step::IfcAddress >, 1 >::getUpperBound(), Step::IfcProduct >, 1 >::getUpperBound(), Step::Bag< T, _lo, _hi >::getUpperBound(), isUnset(), spfToInteger(), and spfToReal().
template<typename T> bool Step::isUnset (RefPtr< T > & t) [inline]
isUnset method for the RefPtr type
References Step::RefPtr< T >::valid().
bool Step::isUnset (const Step::Aggregate & u) [inline]
isUnset method for the Aggregate type
References Step::Aggregate::isUnset().
template<int N> bool Step::isUnset (Binary< N > v) [inline]
isUnset method for the Binary type
References Step::Binary< N >::is_unset().
bool Step::isUnset (Logical v) [inline]
isUnset method for the Logical type
References getUnset().
bool Step::isUnset (Boolean v) [inline]
isUnset method for the Boolean type
References getUnset().
bool Step::isUnset (Real v) [inline]
isUnset method for the Real type
References getUnset().
bool Step::isUnset (Integer v) [inline]
isUnset method for the Integer type
References getUnset().
bool Step::isUnset (BaseObject * v) [inline]
isUnset method for the BaseObject type
References getUnset().
bool Step::isUnset (const BaseObject * v) [inline]
isUnset method for the const BaseObject type
References getUnset().
bool Step::isUnset (const String & v) [inline]
isUnset method for the String type
References getUnset().
bool Step::isUnset (const Unset & u)
Referenced by Step::BaseSPFWriter::writeAttribute().
bool Step::isUnsetEnum (int i) [inline]
isUnset method for the Enumerated type
bool Step::parseList (const char * buffer, std::vector< std::string > & res)
parses a list of strings
Parameters:
buffer the buffer to parse
res the resulting list of strings parsed
Returns:
success or failure
bool Step::removeQuotes (std::string & s)
removes the boundary quotes of a string
Parameters:
s the string to operate on
Returns:
success or failure
template<int N> Binary<N> Step::spfToBinary (const std::string & s) [inline]
spf parsing for Bianry type
References Step::Binary< N >::from_spfstring().
Boolean Step::spfToBoolean (const std::string & s) [inline]
spf parsing for Boolean type
References BFalse, BTrue, and BUnset.
Integer Step::spfToInteger (const std::string & s) [inline]
spf parsing for Integer type
References getUnset().
Logical Step::spfToLogical (const std::string & s) [inline]
spf parsing for Logical type
References LFalse, LTrue, LUnknown, and LUnset.
Real Step::spfToReal (const std::string & s) [inline]
spf parsing for Real type
References getUnset().
Variable Documentation
const char Step::Ampersand = 38
const char Step::Apostrophe = 39
const char Step::Asterix = 42
const char Step::BackSlash = 92
const char Step::Colon = 58
const char Step::Comma = 44
const char Step::CrossHatch = 35
const char Step::DollarSign = 36
const char Step::EqualSign = 61
const char Step::GreaterSign = 62
const char Step::Hyphen = 45
const unsigned long int Step::Id_UNDEF = UINT_MAX
for error handling
const unsigned long int Step::Id_UNSET = 0
for '$' token
const char Step::LeftBracket = 123
const char Step::LeftParenthesis = 40
const char Step::LeftSquareBracket = 91
const char Step::LessSign = 60
const char Step::MinusSign = 45
const char Step::Newline = 10
const char Step::Period = 46
const char Step::PlusSign = 43
const char Step::QuestionMark = 63
const char Step::QuoteMark = 34
const char Step::Return = 13
const char Step::RightBracket = 125
const char Step::RightParenthesis = 41
const char Step::RightSquareBracket = 93
const char Step::Semicolon = 59
const char Step::Slash = 47
const char Step::Space = 32
const char Step::Underscore = 95
const char Step::VerticalSlash = 124