IFC2X3 C++ SDK: Step::Bag< T, _lo, _hi > Class Template Reference
Step::Bag< T, _lo, _hi > Class Template Reference
C++ implementation of EXPRESS container 'BAG' based on multiset.
Inherits std::multiset< T >, and Step::Aggregate.
Public Types
typedef std::multiset< T >
::iterator iterator
typedef std::multiset< T >
::const_iterator const_iterator
typedef std::multiset< T >
::reverse_iterator reverse_iterator
typedef std::multiset< T >
::const_reverse_iterator const_reverse_iterator
Public Member Functions
Bag (bool unset=false)
Bag (const T value[], Integer count) throw (std::range_error)
Bag (const std::vector< T > &value) throw (std::range_error)
Bag (const std::list< T > &value) throw (std::range_error)
virtual ~Bag ()
virtual void insert (const T &_val=getUnset(T())) throw (std::out_of_range)
virtual void erase (iterator &it)
virtual void erase (const T &value)
virtual Integer getUpperBound ()
virtual Integer getLowerBound ()
void operator= (const Bag< T, _lo, _hi > &other)
Detailed Description
template<typename T, Integer _lo = 0, Integer _hi = -1>
class Step::Bag< T, _lo, _hi >
C++ implementation of EXPRESS container 'BAG' based on multiset.
Member Typedef Documentation
template<typename T, Integer _lo = 0, Integer _hi = -1> typedef std::multiset<T>::iterator Step::Bag< T, _lo, _hi >::iterator
template<typename T, Integer _lo = 0, Integer _hi = -1> typedef std::multiset<T>::const_iterator Step::Bag< T, _lo, _hi >::const_iterator
template<typename T, Integer _lo = 0, Integer _hi = -1> typedef std::multiset<T>::reverse_iterator Step::Bag< T, _lo, _hi >::reverse_iterator
template<typename T, Integer _lo = 0, Integer _hi = -1> typedef std::multiset<T>::const_reverse_iterator Step::Bag< T, _lo, _hi >::const_reverse_iterator
Constructor & Destructor Documentation
template<typename T, Integer _lo = 0, Integer _hi = -1> Step::Bag< T, _lo, _hi >::Bag (bool unset = false) [inline]
template<typename T, Integer _lo = 0, Integer _hi = -1> Step::Bag< T, _lo, _hi >::Bag (const T value[], Integer count) throw (std::range_error) [inline]
References Step::Bag< T, _lo, _hi >::insert().
template<typename T, Integer _lo = 0, Integer _hi = -1> Step::Bag< T, _lo, _hi >::Bag (const std::vector< T > & value) throw (std::range_error) [inline]
References Step::Bag< T, _lo, _hi >::insert().
template<typename T, Integer _lo = 0, Integer _hi = -1> Step::Bag< T, _lo, _hi >::Bag (const std::list< T > & value) throw (std::range_error) [inline]
template<typename T, Integer _lo = 0, Integer _hi = -1> virtual Step::Bag< T, _lo, _hi >::~Bag () [inline, virtual]
Member Function Documentation
template<typename T, Integer _lo = 0, Integer _hi = -1> virtual void Step::Bag< T, _lo, _hi >::insert (const T & _val = getUnset(T())) throw (std::out_of_range) [inline, virtual]
References Step::Aggregate::setUnset().
Referenced by Step::Bag< T, _lo, _hi >::Bag().
template<typename T, Integer _lo = 0, Integer _hi = -1> virtual void Step::Bag< T, _lo, _hi >::erase (iterator & it) [inline, virtual]
template<typename T, Integer _lo = 0, Integer _hi = -1> virtual void Step::Bag< T, _lo, _hi >::erase (const T & value) [inline, virtual]
template<typename T, Integer _lo = 0, Integer _hi = -1> virtual Integer Step::Bag< T, _lo, _hi >::getUpperBound () [inline, virtual]
References Step::getUnset().
template<typename T, Integer _lo = 0, Integer _hi = -1> virtual Integer Step::Bag< T, _lo, _hi >::getLowerBound () [inline, virtual]
template<typename T, Integer _lo = 0, Integer _hi = -1> void Step::Bag< T, _lo, _hi >::operator= (const Bag< T, _lo, _hi > & other) [inline]
References Step::Aggregate::isUnset(), and Step::Aggregate::setUnset().