IFC2X3 C++ SDK: Step::Aggregate Class Reference
Step::Aggregate Class Reference
Base Class for Aggregations which need a flag 'unset' This flag is used to distinguish a parameter with an empty list from an unset parameter.
Inherits Step::Referenced.
Inherited by Step::List< double, 2 >, Step::List< double, 2, 3 >, Step::IfcAddress >, 1 >, Step::IfcCompositeCurveSegment >, 1 >, Step::IfcConstraint >, 1 >, Step::IfcGridAxis >, 1 >, Step::IfcGridAxis >, 2, 2 >, Step::IfcMaterialLayer >, 1 >, Step::IfcRepresentation >, 1 >, Step::IfcShapeModel >, 1 >, Step::IfcTableRow >, 1 >, Step::List< long >, Step::List< long, 3, 4 >, Step::List< Step::Binary< 32 >, 1 >, Step::List< Step::Real, 1 >, Step::List< Step::Real, 1, 3 >, Step::List< Step::Real, 2 >, Step::List< Step::Real, 2, 2 >, Step::List< Step::Real, 2, 3 >, Step::List< Step::RefPtr< ifc2x3::IfcActorRole >, 1 >, Step::List< Step::RefPtr< ifc2x3::IfcAxis2Placement3D >, 2 >, Step::List< Step::RefPtr< ifc2x3::IfcCartesianPoint >, 2 >, Step::List< Step::RefPtr< ifc2x3::IfcCartesianPoint >, 3 >, Step::List< Step::RefPtr< ifc2x3::IfcCurveStyleFontPattern >, 1 >, Step::List< Step::RefPtr< ifc2x3::IfcDateTimeSelect >, 1 >, Step::List< Step::RefPtr< ifc2x3::IfcIrregularTimeSeriesValue >, 1 >, Step::List< Step::RefPtr< ifc2x3::IfcLightDistributionData >, 1 >, Step::List< Step::RefPtr< ifc2x3::IfcMaterial >, 1 >, Step::List< Step::RefPtr< ifc2x3::IfcOrientedEdge >, 1 >, Step::List< Step::RefPtr< ifc2x3::IfcProfileDef >, 2 >, Step::List< Step::RefPtr< ifc2x3::IfcRelAssignsToProjectOrder >, 1 >, Step::List< Step::RefPtr< ifc2x3::IfcRepresentationMap >, 1 >, Step::List< Step::RefPtr< ifc2x3::IfcSectionReinforcementProperties >, 1 >, Step::List< Step::RefPtr< ifc2x3::IfcSimpleValue >, 1 >, Step::List< Step::RefPtr< ifc2x3::IfcSoundValue >, 1, 8 >, Step::List< Step::RefPtr< ifc2x3::IfcStructuralLoad >, 1 >, Step::List< Step::RefPtr< ifc2x3::IfcStructuralLoad >, 2 >, Step::List< Step::RefPtr< ifc2x3::IfcSurfaceTexture >, 1 >, Step::List< Step::RefPtr< ifc2x3::IfcTextureVertex >, 3 >, Step::List< Step::RefPtr< ifc2x3::IfcTimeSeriesValue >, 1 >, Step::List< Step::RefPtr< ifc2x3::IfcValue >, 1 >, Step::List< Step::String, 1 >, Step::IfcAppliedValue >, 1 >, Step::IfcClassificationItem >, 1 >, Step::IfcConstraint >, 1 >, Step::IfcCovering >, 1 >, Step::IfcDistributionControlElement >, 1 >, Step::IfcDocumentInformation >, 1 >, Step::IfcDocumentReference >, 1 >, Step::IfcElement >, 1 >, Step::IfcLayeredItem >, 1 >, Step::IfcLibraryReference >, 1 >, Step::IfcObject >, 1 >, Step::IfcObjectDefinition >, 1 >, Step::IfcOrganization >, 1 >, Step::IfcPhysicalQuantity >, 1 >, Step::IfcProduct >, 1 >, Step::IfcProperty >, 1 >, Step::IfcPropertySetDefinition >, 1 >, Step::IfcRoot >, 1 >, Step::IfcSpatialStructureElement >, 1 >, Step::IfcStructuralLoadGroup >, 1 >, Step::IfcStructuralResultGroup >, 1 >, Step::Set< Step::ObsPtr< ifc2x3::IfcAnnotationSurface >, 1, 1 >, Step::Set< Step::ObsPtr< ifc2x3::IfcAppliedValueRelationship > >, Step::Set< Step::ObsPtr< ifc2x3::IfcApprovalActorRelationship > >, Step::Set< Step::ObsPtr< ifc2x3::IfcApprovalRelationship > >, Step::Set< Step::ObsPtr< ifc2x3::IfcClassificationItem > >, Step::Set< Step::ObsPtr< ifc2x3::IfcClassificationItemRelationship >, 0, 1 >, Step::Set< Step::ObsPtr< ifc2x3::IfcComplexProperty >, 0, 1 >, Step::Set< Step::ObsPtr< ifc2x3::IfcCompositeCurve >, 1 >, Step::Set< Step::ObsPtr< ifc2x3::IfcConstraintAggregationRelationship > >, Step::Set< Step::ObsPtr< ifc2x3::IfcConstraintClassificationRelationship > >, Step::Set< Step::ObsPtr< ifc2x3::IfcConstraintRelationship > >, Step::Set< Step::ObsPtr< ifc2x3::IfcDocumentInformation >, 0, 1 >, Step::Set< Step::ObsPtr< ifc2x3::IfcDocumentInformationRelationship > >, Step::Set< Step::ObsPtr< ifc2x3::IfcDocumentInformationRelationship >, 0, 1 >, Step::Set< Step::ObsPtr< ifc2x3::IfcDraughtingCalloutRelationship > >, Step::Set< Step::ObsPtr< ifc2x3::IfcGeometricRepresentationSubContext > >, Step::Set< Step::ObsPtr< ifc2x3::IfcGrid >, 0, 1 >, Step::Set< Step::ObsPtr< ifc2x3::IfcLibraryInformation >, 0, 1 >, Step::Set< Step::ObsPtr< ifc2x3::IfcLocalPlacement > >, Step::Set< Step::ObsPtr< ifc2x3::IfcMappedItem > >, Step::Set< Step::ObsPtr< ifc2x3::IfcMaterialClassificationRelationship >, 0, 1 >, Step::Set< Step::ObsPtr< ifc2x3::IfcMaterialDefinitionRepresentation >, 0, 1 >, Step::Set< Step::ObsPtr< ifc2x3::IfcOrganization > >, Step::Set< Step::ObsPtr< ifc2x3::IfcOrganizationRelationship > >, Step::Set< Step::ObsPtr< ifc2x3::IfcPerson > >, Step::Set< Step::ObsPtr< ifc2x3::IfcPersonAndOrganization > >, Step::Set< Step::ObsPtr< ifc2x3::IfcPhysicalComplexQuantity >, 0, 1 >, Step::Set< Step::ObsPtr< ifc2x3::IfcPresentationLayerAssignment > >, Step::Set< Step::ObsPtr< ifc2x3::IfcProduct >, 1, 1 >, Step::Set< Step::ObsPtr< ifc2x3::IfcProductRepresentation >, 0, 1 >, Step::Set< Step::ObsPtr< ifc2x3::IfcPropertyConstraintRelationship > >, Step::Set< Step::ObsPtr< ifc2x3::IfcPropertyDependencyRelationship > >, Step::Set< Step::ObsPtr< ifc2x3::IfcReferencesValueDocument > >, Step::Set< Step::ObsPtr< ifc2x3::IfcRelAssigns > >, Step::Set< Step::ObsPtr< ifc2x3::IfcRelAssignsToActor > >, Step::Set< Step::ObsPtr< ifc2x3::IfcRelAssignsToControl > >, Step::Set< Step::ObsPtr< ifc2x3::IfcRelAssignsToProcess > >, Step::Set< Step::ObsPtr< ifc2x3::IfcRelAssignsToProduct > >, Step::Set< Step::ObsPtr< ifc2x3::IfcRelAssignsToResource > >, Step::Set< Step::ObsPtr< ifc2x3::IfcRelAssociates > >, Step::Set< Step::ObsPtr< ifc2x3::IfcRelConnectsElements > >, Step::Set< Step::ObsPtr< ifc2x3::IfcRelConnectsPorts >, 0, 1 >, Step::Set< Step::ObsPtr< ifc2x3::IfcRelConnectsPortToElement > >, Step::Set< Step::ObsPtr< ifc2x3::IfcRelConnectsStructuralActivity > >, Step::Set< Step::ObsPtr< ifc2x3::IfcRelConnectsStructuralElement > >, Step::Set< Step::ObsPtr< ifc2x3::IfcRelConnectsStructuralMember > >, Step::Set< Step::ObsPtr< ifc2x3::IfcRelConnectsStructuralMember >, 1 >, Step::Set< Step::ObsPtr< ifc2x3::IfcRelConnectsWithRealizingElements > >, Step::Set< Step::ObsPtr< ifc2x3::IfcRelContainedInSpatialStructure > >, Step::Set< Step::ObsPtr< ifc2x3::IfcRelContainedInSpatialStructure >, 0, 1 >, Step::Set< Step::ObsPtr< ifc2x3::IfcRelCoversBldgElements > >, Step::Set< Step::ObsPtr< ifc2x3::IfcRelCoversBldgElements >, 0, 1 >, Step::Set< Step::ObsPtr< ifc2x3::IfcRelCoversSpaces > >, Step::Set< Step::ObsPtr< ifc2x3::IfcRelCoversSpaces >, 0, 1 >, Step::Set< Step::ObsPtr< ifc2x3::IfcRelDecomposes > >, Step::Set< Step::ObsPtr< ifc2x3::IfcRelDecomposes >, 0, 1 >, Step::Set< Step::ObsPtr< ifc2x3::IfcRelDefines > >, Step::Set< Step::ObsPtr< ifc2x3::IfcRelDefinesByProperties >, 0, 1 >, Step::Set< Step::ObsPtr< ifc2x3::IfcRelDefinesByType >, 0, 1 >, Step::Set< Step::ObsPtr< ifc2x3::IfcRelFillsElement > >, Step::Set< Step::ObsPtr< ifc2x3::IfcRelFillsElement >, 0, 1 >, Step::Set< Step::ObsPtr< ifc2x3::IfcRelFlowControlElements >, 0, 1 >, Step::Set< Step::ObsPtr< ifc2x3::IfcRelInteractionRequirements > >, Step::Set< Step::ObsPtr< ifc2x3::IfcRelProjectsElement > >, Step::Set< Step::ObsPtr< ifc2x3::IfcRelReferencedInSpatialStructure > >, Step::Set< Step::ObsPtr< ifc2x3::IfcRelSequence > >, Step::Set< Step::ObsPtr< ifc2x3::IfcRelServicesBuildings > >, Step::Set< Step::ObsPtr< ifc2x3::IfcRelServicesBuildings >, 0, 1 >, Step::Set< Step::ObsPtr< ifc2x3::IfcRelSpaceBoundary > >, Step::Set< Step::ObsPtr< ifc2x3::IfcRelVoidsElement > >, Step::Set< Step::ObsPtr< ifc2x3::IfcRepresentation > >, Step::Set< Step::ObsPtr< ifc2x3::IfcRepresentationMap >, 0, 1 >, Step::Set< Step::ObsPtr< ifc2x3::IfcShapeAspect > >, Step::Set< Step::ObsPtr< ifc2x3::IfcShapeAspect >, 0, 1 >, Step::Set< Step::ObsPtr< ifc2x3::IfcStructuralAction > >, Step::Set< Step::ObsPtr< ifc2x3::IfcStructuralAnalysisModel > >, Step::Set< Step::ObsPtr< ifc2x3::IfcStructuralAnalysisModel >, 0, 1 >, Step::Set< Step::ObsPtr< ifc2x3::IfcStructuralResultGroup >, 0, 1 >, Step::Set< Step::ObsPtr< ifc2x3::IfcStyledItem >, 0, 1 >, Step::Set< Step::ObsPtr< ifc2x3::IfcTerminatorSymbol >, 0, 2 >, Step::Set< Step::ObsPtr< ifc2x3::IfcTimeSeriesReferenceRelationship >, 0, 1 >, Step::Set< Step::ObsPtr< ifc2x3::IfcTypeObject >, 0, 1 >, Step::Set< Step::ObsPtr< ifc2x3::IfcVirtualGridIntersection > >, Step::Set< Step::RefPtr< ifc2x3::IfcActorSelect >, 1 >, Step::Set< Step::RefPtr< ifc2x3::IfcClassificationNotationFacet >, 1 >, Step::Set< Step::RefPtr< ifc2x3::IfcClassificationNotationSelect >, 1 >, Step::Set< Step::RefPtr< ifc2x3::IfcClosedShell >, 1 >, Step::Set< Step::RefPtr< ifc2x3::IfcConnectedFaceSet >, 1 >, Step::Set< Step::RefPtr< ifc2x3::IfcCurve > >, Step::Set< Step::RefPtr< ifc2x3::IfcCurve >, 1 >, Step::Set< Step::RefPtr< ifc2x3::IfcDerivedUnitElement >, 1 >, Step::Set< Step::RefPtr< ifc2x3::IfcDocumentSelect >, 1 >, Step::Set< Step::RefPtr< ifc2x3::IfcDraughtingCalloutElement >, 1 >, Step::Set< Step::RefPtr< ifc2x3::IfcFace >, 1 >, Step::Set< Step::RefPtr< ifc2x3::IfcFaceBound >, 1 >, Step::Set< Step::RefPtr< ifc2x3::IfcFillAreaStyleTileShapeSelect >, 1 >, Step::Set< Step::RefPtr< ifc2x3::IfcFillStyleSelect >, 1 >, Step::Set< Step::RefPtr< ifc2x3::IfcGeometricSetSelect >, 1 >, Step::Set< Step::RefPtr< ifc2x3::IfcPerson >, 1 >, Step::Set< Step::RefPtr< ifc2x3::IfcPhysicalQuantity >, 1 >, Step::Set< Step::RefPtr< ifc2x3::IfcPresentationStyleAssignment >, 1 >, Step::Set< Step::RefPtr< ifc2x3::IfcPresentationStyleSelect > >, Step::Set< Step::RefPtr< ifc2x3::IfcPresentationStyleSelect >, 1 >, Step::Set< Step::RefPtr< ifc2x3::IfcProfileDef >, 2 >, Step::Set< Step::RefPtr< ifc2x3::IfcProperty >, 1 >, Step::Set< Step::RefPtr< ifc2x3::IfcReinforcementBarProperties >, 1 >, Step::Set< Step::RefPtr< ifc2x3::IfcRelaxation >, 1 >, Step::Set< Step::RefPtr< ifc2x3::IfcRepresentationContext >, 1 >, Step::Set< Step::RefPtr< ifc2x3::IfcRepresentationItem >, 1 >, Step::Set< Step::RefPtr< ifc2x3::IfcShell >, 1 >, Step::Set< Step::RefPtr< ifc2x3::IfcSurfaceStyleElementSelect >, 1, 5 >, Step::Set< Step::RefPtr< ifc2x3::IfcTrimmingSelect >, 1, 2 >, Step::Set< Step::RefPtr< ifc2x3::IfcUnit >, 1 >, Step::Set< Step::RefPtr< ifc2x3::IfcVertexBasedTextureMap >, 1 >, Step::Array< T, _lo, _hi >, Step::Bag< T, _lo, _hi >, Step::List< T, _lo, _hi >, and Step::Set< T, _lo, _hi >.
Public Member Functions
Aggregate (bool b=false)
Constructor from a flag.
bool isUnset () const
Gets the 'unset' flag.
void setUnset (bool b)
Sets the 'unset' flag.
bool toggleUnset ()
Toggle the 'unset' flag.
Protected Attributes
bool m_unset
store if the unset status
Detailed Description
Base Class for Aggregations which need a flag 'unset' This flag is used to distinguish a parameter with an empty list from an unset parameter.
Constructor & Destructor Documentation
Step::Aggregate::Aggregate (bool b = false) [inline]
Constructor from a flag.
Parameters:
b the 'unset' flag
Member Function Documentation
bool Step::Aggregate::isUnset () const [inline]
Gets the 'unset' flag.
Returns:
the 'unset' flag
References m_unset.
Referenced by Step::isUnset(), Step::IfcAddress >, 1 >::operator=(), Step::IfcProduct >, 1 >::operator=(), and Step::Bag< T, _lo, _hi >::operator=().
void Step::Aggregate::setUnset (bool b) [inline]
Sets the 'unset' flag.
Parameters:
b the 'unset' flag
References m_unset.
Referenced by Step::IfcAddress >, 1 >::insert(), Step::IfcProduct >, 1 >::insert(), Step::Bag< T, _lo, _hi >::insert(), Step::IfcAddress >, 1 >::operator=(), Step::IfcProduct >, 1 >::operator=(), Step::Bag< T, _lo, _hi >::operator=(), Step::IfcAddress >, 1 >::push_back(), and Step::IfcAddress >, 1 >::resize().
bool Step::Aggregate::toggleUnset () [inline]
Toggle the 'unset' flag.
Returns:
The new state of the 'unset' flag
References m_unset.
Member Data Documentation
bool Step::Aggregate::m_unset [protected]
store if the unset status
Referenced by isUnset(), setUnset(), and toggleUnset().