IFC2X3 C++ SDK: Step::Binary< N > Class Template Reference
Step::Binary< N > Class Template Reference
C++ Implementation of the EXPRESS Binary type.
Inherits std::bitset< N >.
Public Member Functions
Binary ()
Binary (const Binary< N > &b)
void from_spfstring (const std::string &s)
std::string & to_spfstring ()
int width ()
int width () const
bool fixed_width ()
bool fixed_width () const
bool is_unset ()
Detailed Description
template<int N>
class Step::Binary< N >
C++ Implementation of the EXPRESS Binary type.
Constructor & Destructor Documentation
template<int N> Step::Binary< N >::Binary () [inline]
template<int N> Step::Binary< N >::Binary (const Binary< N > & b) [inline]
Member Function Documentation
template<int N> void Step::Binary< N >::from_spfstring (const std::string & s) [inline]
Referenced by Step::spfToBinary().
template<int N> std::string& Step::Binary< N >::to_spfstring () [inline]
Referenced by Step::BaseSPFWriter::writeAttribute().
template<int N> int Step::Binary< N >::width () [inline]
template<int N> int Step::Binary< N >::width () const [inline]
template<int N> bool Step::Binary< N >::fixed_width () [inline]
template<int N> bool Step::Binary< N >::fixed_width () const [inline]
template<int N> bool Step::Binary< N >::is_unset () [inline]
Referenced by Step::isUnset().